# Site settings
title: Malucky
email: rayma262@gmail.com
description:
  My name is Ray. Welcome to my blog.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.malucky.com" # the base hostname & protocol for your site
github_username: malucky

# Build settings
markdown: kramdown
